import{a as p,S as q,i as l}from"./assets/vendor-DcHCnVjq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const P="28034185-32b171efe234d6a5f1d0d21a7";p.defaults.baseURL="https://pixabay.com/api/";async function f(t,o){return(await p.get("",{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const m=document.querySelector(".gallery"),g=document.querySelector("#loader"),y=document.querySelector(".load-more-btn"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const o=t.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:i,comments:v,downloads:w})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b><span>${r}</span></p>
          <p><b>Views</b><span>${i}</span></p>
          <p><b>Comments</b><span>${v}</span></p>
          <p><b>Downloads</b><span>${w}</span></p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){m.innerHTML=""}function b(){g.classList.add("loader--visible")}function L(){g.classList.remove("loader--visible")}function S(){y.classList.add("load-more-btn--visible")}function c(){y.classList.remove("load-more-btn--visible")}const M=document.querySelector(".form"),R=document.querySelector(".load-more-btn");let d="",s=1,u=0;M.addEventListener("submit",async t=>{t.preventDefault();const o=t.target["search-text"].value.trim();if(o!==""){d=o,s=1,B(),c(),b();try{const a=await f(d,s);if(u=a.totalHits,a.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(a.hits),s*15<u?S():l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(a){l.error({message:"Something went wrong. Please try again.",position:"topRight"}),console.log(a)}finally{L()}}});R.addEventListener("click",async()=>{s+=1,b(),c();try{const t=await f(d,s);h(t.hits),E(),s*15<u?S():(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){l.error({message:"Something went wrong. Please try again.",position:"topRight"}),console.log(t)}finally{L()}});function E(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
